### ISSUE TITLE
Switched the day and night tariffs in the raw with explanation 

### ISSUE THREAD

**Issue by FBosch91** [tribp/DSMR-Fluvius-MQTT-Openhab#4]
Hello,

I guess you have switched the day with night in your raw datagram file with explanation.
In the file you wrote following:

```
1-0:1.8.1(000216.981*kWh)			-> E afname 	nacht
1-0:1.8.2(000310.743*kWh)			-> E afname 	dag
1-0:2.8.1(000258.429*kWh)			-> E injectie	nacht
1-0:2.8.2(000085.695*kWh)			-> E injectie	dag
```

If i read the manual of Fluvius, they tell me the following:
```
1.8.1 = consumption day 
1.8.2 = consumption night 
2.8.1 = injection day 
2.8.2 = injection night
```

Correct me if i am wrong :)

![image](https://user-images.githubusercontent.com/1449216/94303807-b6685e00-ff6e-11ea-935a-abbe7008cde9.png)

**Comment by tribp** [comment]
Hi,

You are right, I forgot to correct the documentation.
The file “p1_fluvius_smartmeter.yaml” is correct so the code works fine :-)

Thx, I will edit the docs.

**Comment by FBosch91** [comment]
Yes indeed, i saw the code is right 👍
